keys:
  - &mac ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ9W6B9WBu7PbMJWdKGFzBLMR1y2IK+kFuSsIWh2fwqg
  # - &desktop ssh-ed25519 AAAAC3...
  # - &linode ssh-ed25519 AAAAC3...

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *mac
          # - *desktop
          # - *linode
